INCLUDE	../star3do.typ

PATH	isd

PACKAGE	ISD_CODE_PACKAGE	isd.shp
	CODE		ISD_CODE			isd.cod
	GFXRES		ISD_ICON_MASK_PMAP_ANIM		isdicons.ani
	GFXRES		ISD_MICON_MASK_PMAP_ANIM	isdmicon.ani
	STRTAB		ISD_RACE_STRINGS		isdtext.txt

PACKAGE	ISD_PACKAGE		isd.shp
	GFXRES		ISD_BIG_MASK_PMAP_ANIM		isd.big
	GFXRES		ISD_MED_MASK_PMAP_ANIM		isd.med
	GFXRES		ISD_SML_MASK_PMAP_ANIM		isd.sml
	GFXRES		ISDLASER_BIG_MASK_PMAP_ANIM	lanbig.ani
	GFXRES		ISDLASER_MED_MASK_PMAP_ANIM	lanmed.ani
	GFXRES		ISDLASER_SML_MASK_PMAP_ANIM	lansml.ani
	GFXRES		ISDFIGHTER_BIG_MASK_PMAP_ANIM	fightbig.ani
	GFXRES		ISDFIGHTER_MED_MASK_PMAP_ANIM	fightmed.ani
	GFXRES		ISDFIGHTER_SML_MASK_PMAP_ANIM	fightsml.ani
	
	GFXRES		ISD_CAPTAIN_MASK_PMAP_ANIM	isdcap.ani
	SNDRES		ISD_SHIP_SOUNDS			isdsound.snd

	MUSICRES	ISD_VICTORY_SONG		isdditty.ogg

