/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SHOFIXTI_COLONY_COLOR_MAP "comm.shofixticolony.colortable"
#define SHOFIXTI_COLONY_CONVERSATION_PHRASES "comm.shofixticolony.dialogue"
