/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ISDFIGHTER_BIG_MASK_PMAP_ANIM "ship.isd.graphics.fighter.large"
#define ISDFIGHTER_MED_MASK_PMAP_ANIM "ship.isd.graphics.fighter.medium"
#define ISDFIGHTER_SML_MASK_PMAP_ANIM "ship.isd.graphics.fighter.small"
#define ISDLASER_BIG_MASK_PMAP_ANIM "ship.isd.graphics.laser.large"
#define ISDLASER_MED_MASK_PMAP_ANIM "ship.isd.graphics.laser.medium"
#define ISDLASER_SML_MASK_PMAP_ANIM "ship.isd.graphics.laser.small"
#define ISD_BIG_MASK_PMAP_ANIM "ship.isd.graphics.isd.large"
#define ISD_CAPTAIN_MASK_PMAP_ANIM "ship.isd.graphics.captain"
#define ISD_ICON_MASK_PMAP_ANIM "ship.isd.icons"
#define ISD_MED_MASK_PMAP_ANIM "ship.isd.graphics.isd.medium"
#define ISD_MICON_MASK_PMAP_ANIM "ship.isd.meleeicons"
#define ISD_SML_MASK_PMAP_ANIM "ship.isd.graphics.isd.small"
