#define YEHATPKUNK_PMAP_ANIM "comm.yehatpkunk.graphics"
#define YEHAT_FONT "comm.yehat.font"
#define PKUNK_FONT "comm.pkunk.font"
#define YEHAT_COLOR_MAP "comm.yehat.colortable"
#define YEHATPKUNK_CONVERSATION_PHRASES "comm.yehatpkunk.dialogue"
#define YEHAT_MUSIC "comm.yehat.music"
