#define HUMAN_COLOR_MAP "comm.human.colortable"
#define HUMAN_COLOR_MAP2 "comm.human.colortable2"
#define HUMAN_PMAP_ANIM "comm.human.graphics"
#define HUMAN_PMAP_ANIM2 "comm.human.graphics2"
#define HUMAN_FONT "comm.human.font"
#define HUMAN_CONVERSATION_PHRASES "comm.human.dialogue"
#define HUMAN_MUSIC "comm.human.music"
