/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define FOONFOON_BEAM_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.beam.large"
#define FOONFOON_BEAM_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.beam.medium"
#define FOONFOON_BEAM_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.beam.small"
#define FOONFOON_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.large"
#define FOONFOON_CAPTAIN_MASK_PMAP_ANIM "ship.foonfoon.graphics.captain"
#define FOONFOON_ICON_MASK_PMAP_ANIM "ship.foonfoon.icons"
#define FOONFOON_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.medium"
#define FOONFOON_MICON_MASK_PMAP_ANIM "ship.foonfoon.meleeicons"
#define FOONFOON_SABRE_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.large"
#define FOONFOON_SABRE_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.medium"
#define FOONFOON_SABRE_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.small"
#define FOONFOON_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.small"
