#define FOONFOON_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.large"
#define FOONFOON_CAPTAIN_MASK_PMAP_ANIM "ship.foonfoon.graphics.captain"
#define FOONFOON_ICON_MASK_PMAP_ANIM "ship.foonfoon.icons"
#define FOONFOON_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.medium"
#define FOONFOON_MICON_MASK_PMAP_ANIM "ship.foonfoon.meleeicons"
#define FOONFOON_BURST_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.burst.large"
#define FOONFOON_BURST_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.burst.medium"
#define FOONFOON_BURST_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.burst.small"
#define FOONFOON_SABRE_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.large"
#define FOONFOON_SABRE_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.medium"
#define FOONFOON_SABRE_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.sabre.small"
#define FOONFOON_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.small"
#define FOONFOON_VICTORY_SONG "ship.foonfoon.ditty"
#define FOONFOON_SHIP_SOUNDS "ship.foonfoon.sounds"
#define FOONFOON_RACE_STRINGS "ship.foonfoon.text"

#include "icode.h"
