#define FOONFOON_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.large"
#define FOONFOON_CAPTAIN_MASK_PMAP_ANIM "ship.foonfoon.graphics.captain"
#define FOONFOON_ICON_MASK_PMAP_ANIM "ship.foonfoon.icons"
#define FOONFOON_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.medium"
#define FOONFOON_MICON_MASK_PMAP_ANIM "ship.foonfoon.meleeicons"
#define FOONFOON_PRIMARY_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffprimary.large"
#define FOONFOON_PRIMARY_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffprimary.medium"
#define FOONFOON_PRIMARY_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffprimary.small"
#define FOONFOON_SECONDARY_BIG_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffsecondary.large"
#define FOONFOON_SECONDARY_MED_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffsecondary.medium"
#define FOONFOON_SECONDARY_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.ffsecondary.small"
#define FOONFOON_SML_MASK_PMAP_ANIM "ship.foonfoon.graphics.typhoon.small"
#define FOONFOON_VICTORY_SONG "ship.foonfoon.ditty"
#define FOONFOON_SHIP_SOUNDS "ship.foonfoon.sounds"
#define FOONFOON_RACE_STRINGS "ship.foonfoon.text"

#include "icode.h"
