/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LURGGOB_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.gob.large"
#define LURGGOB_MED_MASK_PMAP_ANIM "ship.lurg.graphics.gob.medium"
#define LURGGOB_SML_MASK_PMAP_ANIM "ship.lurg.graphics.gob.small"
#define OIL_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.oil.large"
#define OIL_MED_MASK_PMAP_ANIM "ship.lurg.graphics.oil.medium"
#define OIL_SML_MASK_PMAP_ANIM "ship.lurg.graphics.oil.small"
#define LURG_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.large"
#define LURG_CAPTAIN_MASK_PMAP_ANIM "ship.lurg.graphics.captain"
#define LURG_ICON_MASK_PMAP_ANIM "ship.lurg.icons"
#define LURG_MED_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.medium"
#define LURG_MICON_MASK_PMAP_ANIM "ship.lurg.meleeicons"
#define LURG_SML_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.small"
