INCLUDE	../star3do.typ

PATH	lurg

PACKAGE	LURG_CODE_PACKAGE	lurg.shp
	CODE		LURG_CODE			lurg.cod
	GFXRES		LURG_ICON_MASK_PMAP_ANIM	lurgicons.ani
	GFXRES		LURG_MICON_MASK_PMAP_ANIM	lurgmicon.ani
	STRTAB		LURG_RACE_STRINGS		lurgtext.txt

PACKAGE	LURG_PACKAGE		lurg.shp
	GFXRES		LURG_BIG_MASK_PMAP_ANIM	lurg.big
	GFXRES		LURG_MED_MASK_PMAP_ANIM	lurg.med
	GFXRES		LURG_SML_MASK_PMAP_ANIM	lurg.sml
	GFXRES		LURGGOB_BIG_MASK_PMAP_ANIM	spitbig.ani
	GFXRES		LURGGOB_MED_MASK_PMAP_ANIM	spitmed.ani
	GFXRES		LURGGOB_SML_MASK_PMAP_ANIM	spitsml.ani

	GFXRES		LURG_CAPTAIN_MASK_PMAP_ANIM	lurgcap.ani
	SNDRES		LURG_SHIP_SOUNDS		lurgsound.snd

	MUSICRES	LURG_VICTORY_SONG		lurgditty.mod

