#define ANDROSYNTH_COLOR_MAP "comm.androsyn.colortable"
#define ANDROSYNTH_PMAP_ANIM "comm.androsyn.graphics"
#define ANDROSYNTH_FONT "comm.androsyn.font"
#define ANDROSYNTH_CONVERSATION_PHRASES "comm.androsyn.dialogue"
#define ANDROSYNTH_MUSIC "comm.androsyn.music"
