#define LURGGOB_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.gob.large"
#define LURGGOB_MED_MASK_PMAP_ANIM "ship.lurg.graphics.gob.medium"
#define LURGGOB_SML_MASK_PMAP_ANIM "ship.lurg.graphics.gob.small"
#define LURG_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.large"
#define LURG_CAPTAIN_MASK_PMAP_ANIM "ship.lurg.graphics.captain"
#define LURG_ICON_MASK_PMAP_ANIM "ship.lurg.icons"
#define LURG_MED_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.medium"
#define LURG_MICON_MASK_PMAP_ANIM "ship.lurg.meleeicons"
#define LURG_SML_MASK_PMAP_ANIM "ship.lurg.graphics.lurg.small"
#define OIL_BIG_MASK_PMAP_ANIM "ship.lurg.graphics.oil.large"
#define OIL_MED_MASK_PMAP_ANIM "ship.lurg.graphics.oil.medium"
#define OIL_SML_MASK_PMAP_ANIM "ship.lurg.graphics.oil.small"
#define LURG_RACE_STRINGS "ship.lurg.text"
#define LURG_SHIP_SOUNDS "ship.lurg.sounds"
#define LURG_VICTORY_SONG "ship.lurg.ditty"

#include "icode.h"
