INCLUDE	../../star3do.typ

PATH	comm/slaverace

PACKAGE	SLAVERACE_PACKAGE		slaverace.con
	GFXRES			SLAVERACE_PMAP_ANIM			orz.ani
	FONTRES			SLAVERACE_FONT			orz.fon
	MUSICRES		SLAVERACE_MUSIC			orz.mod
	STRTAB			SLAVERACE_CONVERSATION_PHRASES	slaverace.txt
	STRTAB			SLAVERACE_COLOR_MAP			orz.ct
