#define BLASTER_BIG_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.large"
#define BLASTER_MED_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.medium"
#define BLASTER_SML_MASK_PMAP_ANIM "ship.flagship.graphics.blaster.small"
#define EXP_BIG_MASK_PMAP_ANIM "ship.explorer.graphics.exp.large"
#define EXP_ICON_MASK_PMAP_ANIM "ship.explorer.icons"
#define EXP_MED_MASK_PMAP_ANIM "ship.explorer.graphics.exp.medium"
#define EXP_MICON_MASK_PMAP_ANIM "ship.explorer.meleeicons"
#define EXP_SML_MASK_PMAP_ANIM "ship.explorer.graphics.exp.small"
#define PULSE_BIG_MASK_PMAP_ANIM "ship.explorer.graphics.con.large"
#define PULSE_MED_MASK_PMAP_ANIM "ship.explorer.graphics.con.medium"
#define PULSE_SML_MASK_PMAP_ANIM "ship.explorer.graphics.con.small"
#define SIS_BIG_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.large"
#define SIS_CAPTAIN_MASK_PMAP_ANIM "ship.flagship.graphics.captain"
#define SIS_HYPER_MASK_PMAP_ANIM "ship.flagship.graphics.exphyper"
#define SIS_ICON_MASK_PMAP_ANIM "ship.flagship.icons"
#define SIS_MED_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.medium"
#define SIS_ORZ_MASK_PMAP_ANIM "ship.flagship.graphics.exporz"
#define SIS_QUASI_MASK_PMAP_ANIM "ship.flagship.graphics.expquasi"
#define SIS_SML_MASK_PMAP_ANIM "ship.flagship.graphics.flagship.small"
#define SPARK_ONLY_BIG_MASK_PMAP_ANIM "ship.sis_ship.graphics.spark_only.large"
#define SPARK_ONLY_MED_MASK_PMAP_ANIM "ship.sis_ship.graphics.spark_only.medium"
#define SPARK_ONLY_SML_MASK_PMAP_ANIM "ship.sis_ship.graphics.spark_only.small"
#define STUNNER_BIG_MASK_PMAP_ANIM "ship.explorer.graphics.stunner.large"
#define STUNNER_MED_MASK_PMAP_ANIM "ship.explorer.graphics.stunner.medium"
#define STUNNER_SML_MASK_PMAP_ANIM "ship.explorer.graphics.stunner.small"
#define EXP_VICTORY_SONG "ship.explorer.ditty"
#define EXP_SHIP_SOUNDS "ship.explorer.sounds"
#define SIS_SHIP_SOUNDS "ship.flagship.sounds"
#define SIS_VICTORY_SONG "ship.flagship.ditty"

#include "icode.h"
#include "istrtab.h"
