#define ISDFIGHTER_BIG_MASK_PMAP_ANIM "ship.isd.graphics.fighter.large"
#define ISDFIGHTER_MED_MASK_PMAP_ANIM "ship.isd.graphics.fighter.medium"
#define ISDFIGHTER_SML_MASK_PMAP_ANIM "ship.isd.graphics.fighter.small"
#define ISDLASER_BIG_MASK_PMAP_ANIM "ship.isd.graphics.laser.large"
#define ISDLASER_MED_MASK_PMAP_ANIM "ship.isd.graphics.laser.medium"
#define ISDLASER_SML_MASK_PMAP_ANIM "ship.isd.graphics.laser.small"
#define ISD_BIG_MASK_PMAP_ANIM "ship.isd.graphics.isd.large"
#define ISD_CAPTAIN_MASK_PMAP_ANIM "ship.isd.graphics.captain"
#define ISD_ICON_MASK_PMAP_ANIM "ship.isd.icons"
#define ISD_MED_MASK_PMAP_ANIM "ship.isd.graphics.isd.medium"
#define ISD_MICON_MASK_PMAP_ANIM "ship.isd.meleeicons"
#define ISD_SML_MASK_PMAP_ANIM "ship.isd.graphics.isd.small"
#define ISD_RACE_STRINGS "ship.isd.text"
#define ISD_SHIP_SOUNDS "ship.isd.sounds"
#define ISD_VICTORY_SONG "ship.isd.ditty"

#include "icode.h"
