#define BUZZSAW_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.large"
#define BUZZSAW_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.medium"
#define BUZZSAW_SML_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.small"
#define GAS_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.gas.large"
#define GAS_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.gas.medium"
#define GAS_SML_MASK_PMAP_ANIM "ship.slykohr.graphics.gas.small"
#define KOHR_AH_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.large"
#define KOHR_AH_ICON_MASK_PMAP_ANIM "ship.slykohr.icons"
#define KOHR_AH_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.medium"
#define KOHR_AH_MICON_MASK_PMAP_ANIM "ship.slykohr.meleeicons"
#define KOHR_AH_SML_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.small"
#define SLYLANDRO_KOHRAH_CAPTAIN_MASK_PMAP_ANIM "ship.slykohr.graphics.captain"
#define SLYLANDRO_KOHRAH_RACE_STRINGS "ship.slykohr.text"
#define KOHR_AH_SHIP_SOUNDS "ship.slykohr.sounds"
#define KOHR_AH_VICTORY_SONG "ship.slykohr.ditty"

#include "icode.h"
