/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define LURG_COLOR_MAP "comm.lurg.colortable"
#define LURG_CONVERSATION_PHRASES "comm.lurg.dialogue"
