/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SLAVERACE_COLOR_MAP "comm.slaverace.colortable"
#define SLAVERACE_CONVERSATION_PHRASES "comm.slaverace.dialogue"
