/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SYREEN_BASE_COLOR_MAP "comm.syreenbase.colortable"
#define SYREEN_BASE_CONVERSATION_PHRASES "comm.syreenbase.dialogue"
