/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define ISD_BIG_MASK_PMAP_ANIM "ship.isd.graphics.isd.large"
#define ISD_CAPTAIN_MASK_PMAP_ANIM "ship.isd.graphics.captain"
#define ISD_FIGHTER_BIG_MASK_PMAP_ANIM "ship.isd.graphics.fight.large"
#define ISD_FIGHTER_MED_MASK_PMAP_ANIM "ship.isd.graphics.fight.medium"
#define ISD_FIGHTER_SML_MASK_PMAP_ANIM "ship.isd.graphics.fight.small"
#define ISD_FUSION_BIG_MASK_PMAP_ANIM "ship.isd.graphics.fusion.large"
#define ISD_FUSION_MED_MASK_PMAP_ANIM "ship.isd.graphics.fusion.medium"
#define ISD_FUSION_SML_MASK_PMAP_ANIM "ship.isd.graphics.fusion.small"
#define ISD_ICON_MASK_PMAP_ANIM "ship.isd.icons"
#define ISD_MED_MASK_PMAP_ANIM "ship.isd.graphics.isd.medium"
#define ISD_MICON_MASK_PMAP_ANIM "ship.isd.meleeicons"
#define ISD_SML_MASK_PMAP_ANIM "ship.isd.graphics.isd.small"
