INCLUDE	../star3do.typ

PATH	isd

PACKAGE	ISD_CODE_PACKAGE	isd.shp
	CODE		ISD_CODE			isd.cod
	GFXRES		ISD_ICON_MASK_PMAP_ANIM	isdicons.ani
	GFXRES		ISD_MICON_MASK_PMAP_ANIM	isdmicon.ani
	STRTAB		ISD_RACE_STRINGS		isdtext.txt

PACKAGE	ISD_PACKAGE		isd.shp
	GFXRES		ISD_BIG_MASK_PMAP_ANIM	isdbig.ani
	GFXRES		ISD_MED_MASK_PMAP_ANIM	isdmed.ani
	GFXRES		ISD_SML_MASK_PMAP_ANIM	isdsml.ani
	GFXRES		ISD_FUSION_BIG_MASK_PMAP_ANIM	fusion.big
	GFXRES		ISD_FUSION_MED_MASK_PMAP_ANIM	fusion.med
	GFXRES		ISD_FUSION_SML_MASK_PMAP_ANIM	fusion.sml
	GFXRES		ISD_FIGHTER_BIG_MASK_PMAP_ANIM	fight.big
	GFXRES		ISD_FIGHTER_MED_MASK_PMAP_ANIM	fight.med
	GFXRES		ISD_FIGHTER_SML_MASK_PMAP_ANIM	fight.sml
	
	GFXRES		ISD_CAPTAIN_MASK_PMAP_ANIM	isdcap.ani
	SNDRES		ISD_SHIP_SOUNDS		isdsound.snd

	MUSICRES	ISD_VICTORY_SONG		isdditty.mod

