/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define SYREEN_COLOR_MAP "comm.syreenhome.colortable"
#define SYREEN_CONVERSATION_PHRASES "comm.syreenhome.dialogue"
