/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define BUZZSAW_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.large"
#define BUZZSAW_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.medium"
#define BUZZSAW_SML_MASK_PMAP_ANIM "ship.slykohr.graphics.buz.small"
#define GAS_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.gas.large"
#define GAS_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.gas.medium"
#define GAS_SML_MASK_PMAP_ANIM "ship.slykohrh.graphics.gas.small"
#define KOHR_AH_BIG_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.large"
#define KOHR_AH_ICON_MASK_PMAP_ANIM "ship.slykohr.icons"
#define KOHR_AH_MED_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.medium"
#define KOHR_AH_MICON_MASK_PMAP_ANIM "ship.slykohr.meleeicons"
#define KOHR_AH_SML_MASK_PMAP_ANIM "ship.slykohr.graphics.blackurq.small"
#define SLY_KOHR_CAPTAIN_MASK_PMAP_ANIM "ship.slykohr.graphics.captain"
