/* This file was auto-generated by the gen_resfiles utility and
   should not be edited directly.  Modify the master resource list
   instead and regenerate. */

#define HUMAN_COLOR_MAP "comm.human.colortable"
#define HUMAN_CONVERSATION_PHRASES "comm.human.dialogue"
